---
name: Build wit

on:  # yamllint disable-line rule:truthy
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths:
      - 'project/**'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - 'project/**'
      - 'Dockerfile'
  release:
    types:
      - published

env:
  RELEASE: ${{ github.event.action }} == "release" || startsWith(github.ref, 'refs/tags/')

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64/v8
          - linux/amd64

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build wit
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: false
          outputs: type=tar,dest=artifacts
          platforms: ${{ matrix.platform }}

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wit ${{ matrix.platform }}
          path: artifacts/*

      - name: Attach build artifacts to release
        if: ${{ env.RELEASE }}
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build wit
        run: make -C project distrib

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wit mac
          path: project/latest-mac.tar.gz

      - name: Attach build artifacts to release
        if: ${{ env.RELEASE }}
        uses: softprops/action-gh-release@v1
        with:
          files: project/latest-mac.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build wit
        run: make -C project distrib

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wit windows
          path: project/latest-win.tar.gz

      - name: Attach build artifacts to release
        if: ${{ env.RELEASE }}
        uses: softprops/action-gh-release@v1
        with:
          files: project/latest-win.tar.gz
